services:
  bot:
    image: juiim/discord-bot-recom:main
    container_name: discord-bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      NODE_OPTIONS: "--import=./build/shims/fs-glob.js"
